-- AlterTable
ALTER TABLE "ECG" ADD COLUMN     "gain" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "lead" TEXT NOT NULL DEFAULT 'I',
ADD COLUMN     "paperSpeed" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN     "quality" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'mV';
